#include <Arduino.h>
#include "../lib/system/system.hpp"
#include "../lib/user/user.hpp"

void setup() {
	system_setup();
	user_setup();
}

void loop() {	
	system_loop();
	user_loop();
}

/*
curl -X POST \
-H "Content-Type: application/json" \
-d '{"sensor":"buyuk_veri_test","veri":"Bu_bir_test_verisidir_ve_TCP_paket_sinirlarini_asmak_icin_yeterince_uzun_olmasi_gerekiyor_bu_yuzden_surekli_tekrarlayarak_boyutunu_artiriyoruz_0123456789_abcdefghijklmnopqrstuvwxyz_ABCDEFGHIJKLMNOPQRSTUVWXYZ_Bu_bir_test_verisidir_ve_TCP_paket_sinirlarini_asmak_icin_yeterince_uzun_olmasi_gerekiyor_bu_yuzden_surekli_tekrarlayarak_boyutunu_artiriyoruz_0123456789_abcdefghijklmnopqrstuvwxyz_ABCDEFGHIJKLMNOPQRSTUVWXYZ_Bu_bir_test_verisidir_ve_TCP_paket_sinirlarini_asmak_icin_yeterince_uzun_olmasi_gerekiyor_bu_yuzden_surekli_tekrarlayarak_boyutunu_artiriyoruz_0123456789_abcdefghijklmnopqrstuvwxyz_ABCDEFGHIJKLMNOPQRSTUVWXYZ_Bu_bir_test_verisidir_ve_TCP_paket_sinirlarini_asmak_icin_yeterince_uzun_olmasi_gerekiyor_bu_yuzden_surekli_tekrarlayarak_boyutunu_artiriyoruz_0123456789_abcdefghijklmnopqrstuvwxyz_ABCDEFGHIJKLMNOPQRSTUVWXYZ_Bu_bir_test_verisidir_ve_TCP_paket_sinirlarini_asmak_icin_yeterince_uzun_olmasi_gerekiyor_bu_yuzden_surekli_tekrarlayarak_boyutunu_artiriyoruz_0123456789_abcdefghijklmnopqrstuvwxyz_ABCDEFGHIJKLMNOPQRSTUVWXYZ_Bu_bir_test_verisidir_ve_TCP_paket_sinirlarini_asmak_icin_yeterince_uzun_olmasi_gerekiyor_bu_yuzden_surekli_tekrarlayarak_boyutunu_artiriyoruz_0123456789_abcdefghijklmnopqrstuvwxyz_ABCDEFGHIJKLMNOPQRSTUVWXYZ"}' \
http://10.19.20.7/data

curl http://10.19.20.7/data
*/

